### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ezar** [cemolcay/WatchActivityIndicator#4]
I cannot build:
MenuController.swift:41:18: Value of type 'WKInterfaceImage' has no member 'startActivityIndicator'

I installed using pod install but seems doesnt works!

**Comment by cemolcay** [comment]
did you `import WatchActivityIndicator` ?

**Comment by ezar** [comment]
Ahhhh..
We need to import --> import WatchActiviyIndicator
Removing "t"
Regards,

**Comment by ezar** [comment]
No image when I use it.
imageView?.startActivityIndicator()

Nothing happen at watch screen :(

I test current project, and I cannot see image!

![image](https://cloud.githubusercontent.com/assets/42736/24317722/8d38d408-10fa-11e7-9096-640c1fb9de16.png)

**Comment by ezar** [comment]
Any idea?

**Comment by cemolcay** [comment]
it could be a cocoapods related issue.
you could try moving the Activity asset folder which contains the images under Pods/WatchActivityIndicator folder in your project to your watch extension's asset folder.

**Comment by ezar** [comment]
If I download github project and try WatchApp app, have same problem.
Say: 2017-03-25 10:05:41.799 WatchApp Extension[28500:359612] Unable to find image named "Activity" on Watch

![image](https://cloud.githubusercontent.com/assets/42736/24321030/b2701cf2-1142-11e7-84bc-5031c1f3e004.png)

**Comment by ezar** [comment]
Any ideas?
I try to copy images, but doesnt work!

**Comment by cemolcay** [comment]
Like I said before, try to move the resource file that comes with Pods, into your extension's asset folder.
![watch](https://cloud.githubusercontent.com/assets/2419578/24322369/b6775cd8-116b-11e7-8924-014abed7184e.png)

**Comment by ezar** [comment]
I made it, but nothing happen.

**Comment by MaorS** [comment]
I had the same problem, after coping the `Activity` folder from a `Assets.xcassets` into my watch target assets it works
