### ISSUE TITLE
Updating to Swift 5 results in build error

### ISSUE THREAD

**Issue by daviddelmonte** [cemolcay/WatchActivityIndicator#5]
Hi, I'm trying to use your control in WatchOS5. In my app, this code results in a build error:

```
public func showWait() {
        prepareImagesForWait()

        image?.setImage(style == .dot ? EMTLoadingIndicator.dotWaitImage : EMTLoadingIndicator.lineWaitImage)
        image?.startAnimating()
        
        if let controller = controller, let image = image {
            
            controller.animate(withDuration: 0.3, animations: {
                image.setAlpha(1)
            })
        }
        else {
            image?.setAlpha(1)
        }
    }
    
```

The error is: 'animate(withDuration:animations:)' is unavailable

Did I mess up the conversion?

Thanks for any help.

**Comment by cemolcay** [comment]
Hello, I haven't updated the project for a while.
It's updated to Swift 5.0 now. You can update it from cocoapods as well.
It should work fine now.

**Comment by daviddelmonte** [comment]
Brilliant! Many thanks
